 
PetalburgCity_House2_MapScripts::
	.byte 0

PetalburgCity_House2_EventScript_Woman::
	msgbox PetalburgCity_House2_Text_NormanBecameGymLeader, MSGBOX_NPC
	end

PetalburgCity_House2_EventScript_SchoolKid::
	msgbox PetalburgCity_House2_Text_BattledNormanOnce, MSGBOX_NPC
	end

PetalburgCity_House2_Text_NormanBecameGymLeader:
	.string "Erma became Seatag's new\n"
	.string "Gym Leader recently.\p"
	.string "I heard she's a brilliant student\n"
	.string "at the Pokémon School.$"

PetalburgCity_House2_Text_BattledNormanOnce:
	.string "I battled Erma once, but, whew,\n"
	.string "she was way too strong.\p"
	.string "How would I put it?\p"
	.string "I might just be bad enough at\n"
	.string "Pokémon battles.$"

 
