 
RichRivalsHouse_2F_MapScripts::
	.byte 0

RichRivalsHouse_2F_EventScript_DavidNotebook::
	msgbox RichRivalsHouse_2F_Text_DavidNotebook, MSGBOX_SIGN
	end

RichRivalsHouse_2F_EventScript_DavidPC::
	msgbox RichRivalsHouse_2F_Text_DavidPC, MSGBOX_SIGN
	end

RichRivalsHouse_2F_EventScript_DavidGamecube1::
	msgbox RichRivalsHouse_2F_Text_DavidGamecube1, MSGBOX_SIGN
	end

RichRivalsHouse_2F_EventScript_DavidGamecube2::
	msgbox RichRivalsHouse_2F_Text_DavidGamecube2, MSGBOX_SIGN
	end

RichRivalsHouse_2F_Text_DavidNotebook:
	.string "This is an old game guidebook open\n"
	.string "at the cheats page.\p"
	.string "The cover definitely looks old.$"

RichRivalsHouse_2F_Text_DavidPC:
	.string "It's open on a game development forum\n"
	.string "webpage.\p"
	.string "Several users are discussing about\n"
	.string "whether this tutorial explains things\l" 
	.string "well enough.$"

RichRivalsHouse_2F_Text_DavidGamecube1:
	.string "It's a GameCube! There's a lot of\n"
	.string "cool games on that system!$"

RichRivalsHouse_2F_Text_DavidGamecube2:
	.string "Another GameCube! I guess it's useful\n" 
	.string "for LAN play.$"
			  				
